### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by DrRobotnik7** [DrRobotnik7/prework-study-guide#1]
# HTML

## User Story
As a boot camp student,
I want a Prework Study Guide website,
so that I can review all the information I learned throughout Prework.

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Madanaa** [comment]
Hi @DrRobotnik7 can I do this?

**Comment by DrRobotnik7** [comment]
> Hi @DrRobotnik7 can I do this?

Hello! I am on a web development training course and this is part of my pre-work set up, making a website where I can put my notes. So no but thanks for the offer!

**Comment by Madanaa** [comment]
@DrRobotnik7 Thanks for your response!!!
